[package]
name = "vuec_vue3_ssr"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Vue 3 server-side rendering compiler implementation for vuec."
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/vuec_vue3_ssr"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
serde.workspace = true
vuec_ast = { path = "../vuec_ast", version = "0.1.0" }
vuec_codegen = { path = "../vuec_codegen", version = "0.1.0" }
vuec_diagnostics = { path = "../vuec_diagnostics", version = "0.1.0" }
vuec_source = { path = "../vuec_source", version = "0.1.0" }
vuec_vue3_asset = { path = "../vuec_vue3_asset", version = "0.1.0" }
vuec_vue3_core = { path = "../vuec_vue3_core", version = "0.1.0" }
