[package]
name = "vuec_wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WASM binding crate for the vuec Rust Vue compiler."
repository.workspace = true
homepage.workspace = true
documentation = "https://github.com/hamflx/vue-compiler/tree/main/crates/vuec_wasm"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
vuec_sfc = { path = "../vuec_sfc", version = "0.1.0" }
vuec_source = { path = "../vuec_source", version = "0.1.0" }
vuec_vue2 = { path = "../vuec_vue2", version = "0.1.0" }
vuec_vue3_core = { path = "../vuec_vue3_core", version = "0.1.0" }
vuec_vue3_dom = { path = "../vuec_vue3_dom", version = "0.1.0" }
vuec_vue3_ssr = { path = "../vuec_vue3_ssr", version = "0.1.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
wee_alloc.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
