[package]
name = "vuec_vue2"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
vuec_ast = { path = "../vuec_ast" }
vuec_diagnostics = { path = "../vuec_diagnostics" }
vuec_html = { path = "../vuec_html" }
vuec_js = { path = "../vuec_js" }
vuec_source = { path = "../vuec_source" }
