[package]
name = "vuec_js"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_diagnostics.workspace = true
oxc_parser.workspace = true
oxc_span.workspace = true
serde.workspace = true
thiserror.workspace = true
vuec_ast = { path = "../vuec_ast" }
vuec_source = { path = "../vuec_source" }
