[package]
name = "vuec_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vuec"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
vuec_codegen = { path = "../vuec_codegen" }
vuec_diagnostics = { path = "../vuec_diagnostics" }
vuec_sfc = { path = "../vuec_sfc" }
vuec_source = { path = "../vuec_source" }
vuec_vue2 = { path = "../vuec_vue2" }
vuec_vue3_core = { path = "../vuec_vue3_core" }
vuec_vue3_dom = { path = "../vuec_vue3_dom" }
vuec_vue3_ssr = { path = "../vuec_vue3_ssr" }
