[package]
name = "vuec_sfc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Vue single-file component parser and compiler implementation for vuec."
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/vuec_sfc"
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
serde.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
nodejs-semver.workspace = true
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_ast_visit.workspace = true
oxc_parser.workspace = true
oxc_span.workspace = true
vuec_codegen = { path = "../vuec_codegen", version = "0.1.0" }
vuec_ast = { path = "../vuec_ast", version = "0.1.0" }
vuec_diagnostics = { path = "../vuec_diagnostics", version = "0.1.0" }
vuec_html = { path = "../vuec_html", version = "0.1.0" }
vuec_js = { path = "../vuec_js", version = "0.1.0" }
vuec_source = { path = "../vuec_source", version = "0.1.0" }
vuec_style = { path = "../vuec_style", version = "0.1.0" }
vuec_vue3_dom = { path = "../vuec_vue3_dom", version = "0.1.0" }
vuec_vue3_ssr = { path = "../vuec_vue3_ssr", version = "0.1.0" }
vuec_vue3_core = { path = "../vuec_vue3_core", version = "0.1.0" }

[dev-dependencies]
tempfile.workspace = true
