[package]
name = "vuec_sfc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
vuec_codegen = { path = "../vuec_codegen" }
vuec_ast = { path = "../vuec_ast" }
vuec_diagnostics = { path = "../vuec_diagnostics" }
vuec_js = { path = "../vuec_js" }
vuec_source = { path = "../vuec_source" }
vuec_style = { path = "../vuec_style" }
vuec_vue3_dom = { path = "../vuec_vue3_dom" }
vuec_vue3_ssr = { path = "../vuec_vue3_ssr" }
vuec_vue3_core = { path = "../vuec_vue3_core" }
oxc_span.workspace = true
